// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SvMonitoringSystem.Models;
using System;

namespace SvMonitoringSystem.Migrations
{
    [DbContext(typeof(MonitoringContext))]
    [Migration("20180424050703_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SvMonitoringSystem.Models.BasicParameter", b =>
                {
                    b.Property<int>("BasicParameterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acronym");

                    b.Property<string>("DataRange");

                    b.Property<string>("DataSource");

                    b.Property<int>("Pgl");

                    b.Property<int>("Pgn");

                    b.Property<string>("SpnName");

                    b.Property<string>("SpnNameRu");

                    b.HasKey("BasicParameterId");

                    b.ToTable("BasicParameters");
                });

            modelBuilder.Entity("SvMonitoringSystem.Models.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BasicParameterId");

                    b.Property<DateTime>("BasicParameterTimeValue");

                    b.Property<int>("BasicParameterValue");

                    b.Property<int>("VehicleId");

                    b.HasKey("ParameterId");

                    b.HasIndex("BasicParameterId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("SvMonitoringSystem.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Mark");

                    b.Property<string>("ModelType");

                    b.Property<string>("OverallDimensions");

                    b.Property<int>("UsefulVolume");

                    b.Property<string>("VehicleType");

                    b.Property<int>("YearIssue");

                    b.Property<int>("СarryingСapacity");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SvMonitoringSystem.Models.Parameter", b =>
                {
                    b.HasOne("SvMonitoringSystem.Models.BasicParameter", "BasicParameter")
                        .WithMany()
                        .HasForeignKey("BasicParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SvMonitoringSystem.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
